// packages/react/dev/App.tsx
import React from "react";
import { useState } from "react";
import "./App.css";
import { BottomSheet } from "../src/main";

const App = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [count, setCount] = useState(0);

  const [props, setProps] = useState({
    snapPoint: "auto",
    isBackdrop: true,
    isDragHandle: true,
    isFullscreen: true,
    isPersistent: false,
    isScrollLock: true,
  });

  const handleIncrement = () => {
    setCount(count + 1);
  };

  const handleClose = () => {
    setIsOpen(false);
  };

  return (
    <>
      <h2>@web-bottom-sheet/react</h2>
      <button onClick={() => setIsOpen(true)}>open</button>

      <BottomSheet
        open={isOpen}
        snapPoint={props.snapPoint}
        isBackdrop={props.isBackdrop}
        isDragHandle={props.isDragHandle}
        isFullscreen={props.isFullscreen}
        isPersistent={props.isPersistent}
        isScrollLock={props.isScrollLock}
        onClose={handleClose}
        onChangePositionStatus={(e) => {
          // console.log("onChangePositionStatus");
          console.log("onChangePositionStatus", e.detail.positionStatus);
        }}
      >
        <div className="panel">
          <p>This is contents.</p>
          <button onClick={handleClose}>close</button>
          <button
            onClick={(e) => {
              handleIncrement();
            }}
          >
            count: {count}
          </button>
        </div>
      </BottomSheet>
    </>
  );
};

export default App;

// packages/vue/dev/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { BottomSheet } from "../src/main";

const isOpen = ref(false);

const option = ref({
  snapPoint: "auto",
  isBackdrop: true,
  isDragHandle: true,
  isFullscreen: true,
  isPersistent: false,
  isScrollLock: true,
});
</script>

<template>
  <h2>@web-bottom-sheet/vue</h2>

  <div class="input-text">
    <label for="snapPoint">snapPoint</label>
    <input
      v-model="option.snapPoint"
      id="snapPoint"
      name="snapPoint"
      type="text"
    />
  </div>

  <div class="input-checkbox">
    <label for="isBackdrop">isBackdrop</label>
    <input
      v-model="option.isBackdrop"
      id="isBackdrop"
      name="isBackdrop"
      type="checkbox"
    />
  </div>

  <div class="input-checkbox">
    <label for="isDragHandle">isDragHandle</label>
    <input
      v-model="option.isDragHandle"
      id="isDragHandle"
      name="isDragHandle"
      type="checkbox"
    />
  </div>

  <div class="input-checkbox">
    <label for="isFullscreen">isFullscreen</label>
    <input
      v-model="option.isFullscreen"
      id="isFullscreen"
      name="isFullscreen"
      type="checkbox"
    />
  </div>

  <div class="input-checkbox">
    <label for="isPersistent">isPersistent</label>
    <input
      v-model="option.isPersistent"
      id="isPersistent"
      name="isPersistent"
      type="checkbox"
    />
  </div>

  <div class="input-checkbox">
    <label for="isScrollLock">isScrollLock</label>
    <input
      v-model="option.isScrollLock"
      id="isScrollLock"
      name="isScrollLock"
      type="checkbox"
    />
  </div>

  <hr />

  <button @click="isOpen = true">open</button>

  <BottomSheet
    :open="isOpen"
    @on-close="isOpen = false"
    :snap-point="option.snapPoint"
    :is-backdrop="option.isBackdrop"
    :is-drag-handle="option.isDragHandle"
    :is-fullscreen="option.isFullscreen"
    :is-persistent="option.isPersistent"
    :is-scroll-lock="option.isScrollLock"
  >
    <div class="panel">
      <p>This is contents.</p>
      <button @click="isOpen = false">close</button>
    </div>
  </BottomSheet>
</template>

<style scoped>
web-bottom-sheet::part(dialog) {
  background-color: #242424;
  border-radius: 8px 8px 0 0;
  box-sizing: border-box;
}

web-bottom-sheet::part(dialog):focus {
  outline-color: #646cff;
}

web-bottom-sheet::part(dialog)::backdrop {
  background-color: rgb(0 0 0 / 50%);
  -webkit-backdrop-filter: blur(2px);
  backdrop-filter: blur(2px);
}

@media (prefers-color-scheme: light) {
  web-bottom-sheet::part(dialog) {
    background-color: #ffffff;
  }
}
.panel {
  padding: 16px;
}
</style>
