// packages/react/src/components/BottomSheet.tsx
import { resister, type WebBottomSheetProps } from "@web-bottom-sheet/core";
import { useEffect, useRef, type PropsWithChildren } from "react";

type BottomSheetProps = PropsWithChildren<
  WebBottomSheetProps & {
    onClose: () => void;
  }
>;

export const BottomSheet = (props: BottomSheetProps) => {
  const {
    open,
    isBackdrop,
    isDragHandle,
    isFullscreen,
    isPersistent,
    isScrollLock,
    onClose,
    children,
  } = props;

  const webBottomSheetRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    resister(["web-bottom-sheet"]);
  }, []);

  useEffect(() => {
    if (webBottomSheetRef.current) {
      webBottomSheetRef.current.addEventListener("close", onClose);
    }

    return () => {
      if (webBottomSheetRef.current) {
        webBottomSheetRef.current.removeEventListener("close", onClose);
      }
    };
  }, [onClose]);

  return (
    <web-bottom-sheet
      ref={webBottomSheetRef}
      open={open ? "" : undefined}
      is-backdrop={isBackdrop ? "" : undefined}
      is-drag-handle={isDragHandle ? "" : undefined}
      is-fullscreen={isFullscreen ? "" : undefined}
      is-persistent={isPersistent ? "" : undefined}
      is-scroll-lock={isScrollLock ? "" : undefined}
    >
      {children}
    </web-bottom-sheet>
  );
};

// packages/vue/src/components/BottomSheet.vue
<script setup lang="ts">
import { useVModel } from "@vueuse/core";
import { resister, type WebBottomSheetProps } from "@web-bottom-sheet/core";
import { onMounted, ref } from "vue";

const props = defineProps<{
  open?: WebBottomSheetProps["open"];
  isBackdrop?: WebBottomSheetProps["isBackdrop"];
  isDragHandle?: WebBottomSheetProps["isDragHandle"];
  isFullscreen?: WebBottomSheetProps["isFullscreen"];
  isPersistent?: WebBottomSheetProps["isPersistent"];
  isScrollLock?: WebBottomSheetProps["isScrollLock"];
}>();

const emit = defineEmits<{
  (event: "close", value: boolean): void;
  (event: "loaded"): void;
  (event: "update:open", value: boolean): void;
}>();
const modelValue = useVModel(props, "open", emit);
const onClose = () => {
  emit("close", false);
  modelValue.value = false;
};
const onLoaded = () => {
  emit("loaded");
};

const isLoaded = ref(false);
onMounted(() => {
  resister(["web-bottom-sheet"]);

  customElements.whenDefined("web-bottom-sheet").then(() => {
    isLoaded.value = true;
    onLoaded();
  });
});
</script>

<template>
  <template v-if="isLoaded">
    <web-bottom-sheet
      :open="modelValue"
      :is-backdrop="props.isBackdrop ? '' : null"
      :is-drag-handle="props.isDragHandle ? '' : null"
      :is-fullscreen="props.isFullscreen ? '' : null"
      :is-persistent="props.isPersistent ? '' : null"
      :is-scroll-lock="props.isScrollLock ? '' : null"
      @close="onClose"
    >
      <slot />
    </web-bottom-sheet>
  </template>
  <template v-else>
    <div id="web-bottom-sheet-skeleton" />
  </template>
</template>
